/**
 * The actual PostCSS plugin.
 *
 * Two transforms, both deliberate:
 *
 *  1. **`:root` -> host selector.** Tailwind v4 emits `@theme` design tokens
 *     and the user's own `@layer base { :root { … } }` block onto `:root`.
 *     Inside a shadow root, `:root` is the shadow root's host *document* —
 *     which we can't reach from a stylesheet adopted into the shadow. We
 *     rewrite `:root` (and the `@layer base` wrappers that wrap it) to
 *     `:host` so the vars declare on the shadow boundary and cascade in.
 *
 *  2. **`theme(:host)` rewrite.** Some integrations write `theme(:host)` /
 *     `theme(:where(:host, :host *))` inside their CSS to mean "give me the
 *     in-shadow-flavored host selector." We resolve that to the configured
 *     hostSelector at build time. (`theme(:host)` is shadowkit syntax —
 *     Tailwind itself doesn't ship it; the plugin treats it like a macro.)
 *
 * `emitAsModule` is a separate concern: when on, the plugin attaches a JS
 * module string to `result.messages` keyed by `type: "shadowkit-tailwind-module"`,
 * which build adapters (Vite, esbuild, Rollup) can pick up and write to disk.
 */

import type { PluginCreator, Result, Root } from "postcss";
import type { ShadowkitTailwindOptions } from "./index.js";
import { PLUGIN_NAME } from "./index.js";

const ROOT_RE = /(^|[\s,])\:root(?![\w-])/g;
const THEME_HOST_RE = /theme\(\s*:host(?:[^)]*)?\)/g;

interface ModuleMessage {
  type: "shadowkit-tailwind-module";
  plugin: string;
  path: string;
  source: string;
}

function buildModule(css: string, modulePath: string): string {
  // Default export is a CSS string; callers do `import css from '…'` and pass
  // it to `injectTailwind(shadow, css)`. We keep the file dependency-free so
  // build tools don't need a special loader.
  const escaped = JSON.stringify(css);
  return `// generated by ${PLUGIN_NAME} — do not edit.\n` +
    `// source: ${modulePath}\n` +
    `const css = ${escaped};\n` +
    `export default css;\n`;
}

function rewriteSelectors(root: Root, hostSelector: string): void {
  root.walkRules((rule) => {
    const next = rule.selector.replace(ROOT_RE, (_, lead) => `${lead}${hostSelector}`);
    if (next !== rule.selector) rule.selector = next;
  });
}

function rewriteThemeMacro(root: Root, hostSelector: string): void {
  root.walkDecls((decl) => {
    if (!decl.value.includes("theme(")) return;
    const next = decl.value.replace(THEME_HOST_RE, hostSelector);
    if (next !== decl.value) decl.value = next;
  });
  root.walkRules((rule) => {
    if (!rule.selector.includes("theme(")) return;
    const next = rule.selector.replace(THEME_HOST_RE, hostSelector);
    if (next !== rule.selector) rule.selector = next;
  });
}

function attachModule(
  result: Result,
  css: string,
  options: ShadowkitTailwindOptions
): void {
  if (!options.emitAsModule) return;
  const message: ModuleMessage = {
    type: "shadowkit-tailwind-module",
    plugin: PLUGIN_NAME,
    path: options.moduleOutputPath ?? "shadowkit-tailwind.css.js",
    source: buildModule(css, options.moduleOutputPath ?? "<inline>"),
  };
  result.messages.push(message);
}

const creator: PluginCreator<ShadowkitTailwindOptions> = (
  options: ShadowkitTailwindOptions = {}
) => {
  const hostSelector = options.hostSelector ?? ":host";
  return {
    postcssPlugin: PLUGIN_NAME,
    OnceExit(root, { result }) {
      rewriteSelectors(root, hostSelector);
      rewriteThemeMacro(root, hostSelector);
      attachModule(result, root.toString(), options);
    },
  };
};
creator.postcss = true;

export default creator;
